config/routes.rb
Rails.application.routes.draw do
  root "courses#index"
  get 'about', to: "pages#about"

  resource :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true, length: {  minimum: 3, maximum: 15 }
  validates :name, presence: true, length: {  minimum: 5, maximum: 30 }
  validates :description, presence: true, length: {  minimum: 5, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Course Listing</h3>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <a href="#">Enroll</a>
          <a href="#">Info</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h2>This is courses new page</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <div class="container">
          <div class="nav-wrapper">
            <a href="#" class="brand-logo right">Tech University</a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
              <li><%= link_to 'Courses', root_path %></li>
              <li><%= link_to 'Enrollments', about_path %></li>
              <li><%= link_to 'Account', new_courses_path %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Tech University</h5>
            <p class="grey-text text-lighten-4">This is future of training.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">About Us</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2014 Copyright Tech University
        <a class="grey-text text-lighten-4 right" href="#!">About us</a>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is about page </h1>